# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.0775719, -0.629287, 0.663759]
rotation: [0.69334, 0.716474, -0.0625659, 0.0450595]
frame_id: camera_color_optical_frame
child_frame_id: setup1/panda_link0
